# Generated by Django 6.0.6 on 2026-06-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approvalhistory',
            name='api_approval_quote_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotation',
            name='api_quotation_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotation',
            name='api_quotation_createdat_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotation',
            name='api_quotation_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotation',
            name='api_quotation_expiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotation',
            name='api_quotation_status_creator_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationcomment',
            name='api_comment_quote_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationversion',
            name='api_version_quote_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationviewlog',
            name='api_viewlog_quote_time_idx',
        ),
    ]
